In [2]:
# importações
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [5]:
URL = "https://books.toscrape.com/"
res = requests.get(URL)
bs = BeautifulSoup(res.text,"lxml")

In [7]:
bs.find("h1").get_text(strip=True)

'All products'

In [65]:
livros = bs.find_all("article",class_="product_pod")
dados = []
for livro in livros:
    titulo = livro.find("h3").find("a")["title"]
    preco = livro.find("p",class_="price_color").get_text(strip=True)
    estoque = livro.find("p",class_="instock availability").get_text(strip=True)
    avaliacao = livro.find("p",class_="star-rating")["class"][1]
    dados.append({"titulo":titulo,"preco":preco,"estoque":estoque,"avaliacao":avaliacao})
livros_df = pd.DataFrame(dados)
livros_df

,titulo,preco,estoque,avaliacao
0,A Light in the Attic,Â£51.77,In stock,Three
1,Tipping the Velvet,Â£53.74,In stock,One
2,Soumission,Â£50.10,In stock,One
3,Sharp Objects,Â£47.82,In stock,Four
4,Sapiens: A Brief History of Humankind,Â£54.23,In stock,Five
5,The Requiem Red,Â£22.65,In stock,One
6,The Dirty Little Secrets of Getting Your Dream...,Â£33.34,In stock,Four
7,The Coming Woman: A Novel Based on the Life of...,Â£17.93,In stock,Three
8,The Boys in the Boat: Nine Americans and Their...,Â£22.60,In stock,Four
9,The Black Maria,Â£52.15,In stock,One
10,"Starving Hearts (Triangular Trade Trilogy, #1)",Â£13.99,In stock,Two
11,Shakespeare's Sonnets,Â£20.66,In stock,Four
12,Set Me Free,Â£17.46,In stock,Five
13,Scott Pilgrim's Precious Little Life (Scott Pi...,Â£52.29,In stock,Five
14,Rip it Up and Start Again,Â£35.02,In stock,Five
15,Our Band Could Be Your Life: Scenes from the A...,Â£57.25,In stock,Three
16,Olio,Â£23.88,In stock,One
17,Mesaerion: The Best Science Fiction Stories 18...,Â£37.59,In stock,One
18,Libertarianism for Beginners,Â£51.33,In stock,Two
19,It's Only the Himalayas,Â£45.17,In stock,Two

In [123]:
URL = "https://quotes.toscrape.com/"
res = requests.get(URL)
bs = BeautifulSoup(res.text,"lxml")

quotes = bs.find_all("div",class_="quote")
#tags = bs.find_all("div",class_="tags")
todos = []
for quote in quotes:
    citacao = quote.find("span",class_="text").get_text(strip=True)
    autor = quote.find("small",class_="author").get_text(strip=True)
    
    dados_tag = []
    for tag in quote.find_all("a",class_="tag"):
        dados_tag.append(tag.get_text(strip=True))

    todos.append({"citacao":citacao,"autor":autor,"tag":dados_tag})

citacao = pd.DataFrame(todos)
citacao

,citacao,autor,tag
0,“The world as we have created it is a process ...,Albert Einstein,"[change, deep-thoughts, thinking, world]"
1,"“It is our choices, Harry, that show what we t...",J.K. Rowling,"[abilities, choices]"
2,“There are only two ways to live your life. On...,Albert Einstein,"[inspirational, life, live, miracle, miracles]"
3,"“The person, be it gentleman or lady, who has ...",Jane Austen,"[aliteracy, books, classic, humor]"
4,"“Imperfection is beauty, madness is genius and...",Marilyn Monroe,"[be-yourself, inspirational]"
5,“Try not to become a man of success. Rather be...,Albert Einstein,"[adulthood, success, value]"
6,“It is better to be hated for what you are tha...,André Gide,"[life, love]"
7,"“I have not failed. I've just found 10,000 way...",Thomas A. Edison,"[edison, failure, inspirational, paraphrased]"
8,“A woman is like a tea bag; you never know how...,Eleanor Roosevelt,[misattributed-eleanor-roosevelt]
9,"“A day without sunshine is like, you know, nig...",Steve Martin,"[humor, obvious, simile]"

In [192]:
URL = "https://webscraper.io/test-sites/pagination"
import re

res = requests.get(URL)
bs = BeautifulSoup(res.text,"lxml")

cars = bs.find_all("div",class_="card")

todos = []

for car in cars:
    carro = car.find("h3").find("a").get_text(strip=True)
    modelo = car.find("p",class_="description").get_text(strip=True)
    dados = car.find_all("p",class_="card-text")
    ano = dados[0].get_text(strip=True)
    ano = ano.replace("Year:","").strip()
    pais = dados[1].get_text(strip=True)
    pais = pais.replace("Country of origin:","").strip()
    milhagem = dados[2].get_text(strip=True)
    milhagem = milhagem.replace("Mileage:","").strip()
    todos.append({"carro":carro,"modelo":modelo,"ano":ano,"pais":pais,"milhagem":milhagem})
    
todos = pd.DataFrame(todos)
todos

,carro,modelo,ano,pais,milhagem
0,Mercedes-Benz W123 280E 1955,Uncompromising Stuttgart saloon,1955,United Kingdom,104 338 km
1,BMW E24 635CSi 1954,Shark-nose grand tourer,1954,Germany,189 886 km
2,Jaguar XJ6 1983,Silky British luxury saloon,1983,Germany,119 395 km
3,Nissan 300ZX Z31 1966,Angular Japanese sports coupe,1966,Japan,134 738 km
4,Ferrari F40 1984,Raw Prancing Horse icon,1984,Italy,141 828 km
5,Mercedes-Benz W123 280E 1972,"Early W123, driver condition",1972,Germany,31 412 km

In [205]:
URL = "https://books.toscrape.com/"
res = requests.get(URL)
bs = BeautifulSoup(res.text,"lxml")

import time

todos = []
for pagina in range (1,8):
    url = f"https://books.toscrape.com/catalogue/page-{pagina}.html"
    r = requests.get(url)
    if res.status_code != 200:
        break
    s = BeautifulSoup(res.text,"lxml")
    for livro in s.find_all("article",class_="product_pod"):
        preco = livro.find("p",class_="price_color").get_text(strip=True)
        preco = preco.replace("Â£","").strip()
        todos.append({
            "titulo":livro.find("h3").find("a")["title"],
            "preco": preco,
            "estoque":livro.find("p",class_="instock availability").get_text(strip=True),
            "nota":livro.find("p",class_="star-rating")["class"][1],
        })
        time.sleep(1)
todos = pd.DataFrame(todos)
todos

                                                titulo  preco   estoque   nota
0                                 A Light in the Attic  51.77  In stock  Three
1                                   Tipping the Velvet  53.74  In stock    One
2                                           Soumission  50.10  In stock    One
3                                        Sharp Objects  47.82  In stock   Four
4                Sapiens: A Brief History of Humankind  54.23  In stock   Five
..                                                 ...    ...       ...    ...
135  Our Band Could Be Your Life: Scenes from the A...  57.25  In stock  Three
136                                               Olio  23.88  In stock    One
137  Mesaerion: The Best Science Fiction Stories 18...  37.59  In stock    One
138                       Libertarianism for Beginners  51.33  In stock    Two
139                            It's Only the Himalayas  45.17  In stock    Two

[140 rows x 4 columns]