## DATA WRANGLING
## Arquivo de apoio para estudo de data wrangling¶

## Notas aula MBA SUP/Esalq - Módulo Data Wrangling V

In [1]:
# IMPORTAÇÃO DE BANCOS DE DADOS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# pip install xlrd # pacote dependência que read_excel usa para ler arquivos na extensão .xls

In [2]:
# Datasets
dados_filmes = pd.read_csv('(5.2) Filmes Streaming.csv', sep=',')
dados_series = pd.read_csv('(5.3) Séries Streaming.csv', sep=',')

In [3]:
dados_filmes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9515 entries, 0 to 9514
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       9515 non-null   int64
 1   ID               9515 non-null   int64
 2   Title            9515 non-null   object
 3   Year             9515 non-null   int64
 4   Age              5338 non-null   object
 5   IMDb             9309 non-null   object
 6   Rotten Tomatoes  9508 non-null   object
 7   Netflix          9515 non-null   int64
 8   Hulu             9515 non-null   int64
 9   Prime Video      9515 non-null   int64
 10  Disney+          9515 non-null   int64
 11  Type             9515 non-null   int64
 12  Directors        9104 non-null   object
 13  Genres           9399 non-null   object
 14  Country          9261 non-null   object
 15  Language         9185 non-null   object
 16  Runtime          9196 non-null   float64
dtypes: float64(1), int64(8), object(8)
memory usage: 1.2+ MB

In [4]:
dados_series.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5368 entries, 0 to 5367
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       5368 non-null   int64
 1   ID               5368 non-null   int64
 2   Title            5368 non-null   object
 3   Year             5368 non-null   int64
 4   Age              3241 non-null   object
 5   IMDb             4406 non-null   object
 6   Rotten Tomatoes  5368 non-null   object
 7   Netflix          5368 non-null   int64
 8   Hulu             5368 non-null   int64
 9   Prime Video      5368 non-null   int64
 10  Disney+          5368 non-null   int64
 11  Type             5368 non-null   int64
dtypes: int64(8), object(4)
memory usage: 503.4+ KB

In [5]:
# Selecionando as variáveis de interesse
dados_filmes = dados_filmes.iloc[:,0:12]

In [6]:
# Junção de dados
dados_completo = pd.concat([dados_filmes,dados_series],ignore_index=True)

In [7]:
# Remoção da variável indesejada
dados_completo.drop(columns=("Unnamed: 0"),inplace=True)

In [8]:
# Extrair notas
dados_completo["Ajuste_IMDB"] = dados_completo["IMDb"].str.slice(0,4)
dados_completo["Ajuste_Rotten"]=dados_completo['Rotten Tomatoes'].str.slice(0,3)

In [9]:
# Ajustar a string e transformar para float
# A função str.rstrip() remove o caractere ao final da string
# str.rstrip — remove caracteres apenas do lado direito (final) da string
# str.strip — remove caracteres dos dois lados (início e fim)
# str.lstrip — remove só do lado esquerdo (início)
dados_completo['Ajuste_IMDB']=dados_completo['Ajuste_IMDB'].str.rstrip('/').astype("float")

In [10]:
dados_completo['Ajuste_Rotten']=dados_completo['Ajuste_Rotten'].str.rstrip('/').astype("float")

In [11]:
# Atribuindo labels
muda_numeros = {0:"filme",1:"serie"}
dados_completo = dados_completo.assign(tipo = dados_completo["Type"].map(muda_numeros))
# Aplica o dicionário em cada elemento da coluna Type. Onde encontra 0 coloca 'filme',
# onde encontra 1 coloca 'série'
# Qualquer valor fora do dicionário vira NaN.

In [12]:
dados_completo

,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Ajuste_IMDB,Ajuste_Rotten,tipo
0,1,The Irishman,2019,18+,7.8/10,98/100,1,0,0,0,0,7.8,98.0,filme
1,2,Dangal,2016,7+,8.4/10,97/100,1,0,0,0,0,8.4,97.0,filme
2,3,David Attenborough: A Life on Our Planet,2020,7+,9.0/10,95/100,1,0,0,0,0,9.0,95.0,filme
3,4,Lagaan: Once Upon a Time in India,2001,7+,8.1/10,94/100,1,0,0,0,0,8.1,94.0,filme
4,5,Roma,2018,18+,7.7/10,94/100,1,0,0,0,0,7.7,94.0,filme
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14878,5713,Paradise Islands,2017,NaN,NaN,10/100,0,0,0,1,1,NaN,10.0,serie
14879,5714,Mexico Untamed,2018,NaN,NaN,10/100,0,0,0,1,1,NaN,10.0,serie
14880,5715,Wild Centeral America,2020,NaN,NaN,10/100,0,0,0,1,1,NaN,10.0,serie
14881,5716,Wild Russia,2018,NaN,NaN,10/100,0,0,0,1,1,NaN,10.0,serie
14882,5717,Fearless Adventures with Jack Randall,2018,NaN,NaN,10/100,0,0,0,1,1,NaN,10.0,serie

In [13]:
# Agrupando o dataset
descritivas = dados_completo.groupby(['tipo'])

In [14]:
descritivas["Ajuste_IMDB"].describe().T

tipo         filme        serie
count  9309.000000  4406.000000
mean      6.156311     7.086019
std       1.163573     1.114977
min       1.100000     1.100000
25%       5.500000     6.500000
50%       6.300000     7.300000
75%       7.000000     7.900000
max       9.800000     9.600000

In [15]:
descritivas["Ajuste_Rotten"].describe().T

tipo         filme        serie
count  9508.000000  5368.000000
mean     53.545015    47.220380
std      13.197673    19.555753
min      10.000000    10.000000
25%      44.000000    36.000000
50%      52.000000    48.000000
75%      62.000000    60.000000
max      98.000000   100.000000

In [16]:
# Criar um indicador com os melhores filmes e série, segundo avaliação IMDB e Rotten
# Vamos usar o percentil como referência
melhores_series=dados_completo[dados_completo['tipo']=="serie"]
melhores_filmes=dados_completo[dados_completo['tipo']=="filme"]

In [17]:
melhores_series[["Ajuste_IMDB","Ajuste_Rotten"]].quantile(0.95)

Ajuste_IMDB       8.5
Ajuste_Rotten    79.0
Name: 0.95, dtype: float64

In [24]:
# gerando dados
melhores_series = melhores_series.assign(Categ_IMDB = pd.qcut\
                                         (melhores_series['Ajuste_IMDB'],q=[0,0.95,1],labels=["menores","maiores"]))

In [27]:
melhores_series = melhores_series.assign(Categ_Rotten = \
                                         pd.qcut(melhores_series['Ajuste_Rotten'],q=[0,0.95,1],\
                                         labels=["menores","maiores"]))

In [29]:
melhores_series=melhores_series[(melhores_series['Categ_IMDB']=="maiores")&\
(melhores_series['Categ_Rotten']=="maiores")].sort_values(["Ajuste_Rotten","Ajuste_IMDB"]\
                                                          ,ascending=False)

In [33]:
#%% Filmes
# Identificar os que estão com melhores notas nas duas avaliações
# Usar o percentil 95 das notas como referência
melhores_series[["Ajuste_IMDB","Ajuste_Rotten"]].quantile(0.95)

Ajuste_IMDB       9.24
Ajuste_Rotten    94.40
Name: 0.95, dtype: float64

In [38]:
# Gerando dados Melhores Filmes
melhores_filmes = melhores_filmes.assign(Categ_IMDB=pd.qcut(melhores_filmes['Ajuste_IMDB'],\
                                                            q=[0,0.95,1],labels=["maiores","menores"]))

In [40]:
melhores_filmes = melhores_filmes.assign\
(Categ_Rotten = pd.qcut(melhores_filmes['Ajuste_Rotten'],q=[0,0.95,1],labels=["maiores","menores"]))

In [41]:
melhores_filmes

,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Ajuste_IMDB,Ajuste_Rotten,tipo,Categ_IMDB,Categ_Rotten
0,1,The Irishman,2019,18+,7.8/10,98/100,1,0,0,0,0,7.8,98.0,filme,maiores,menores
1,2,Dangal,2016,7+,8.4/10,97/100,1,0,0,0,0,8.4,97.0,filme,menores,menores
2,3,David Attenborough: A Life on Our Planet,2020,7+,9.0/10,95/100,1,0,0,0,0,9.0,95.0,filme,menores,menores
3,4,Lagaan: Once Upon a Time in India,2001,7+,8.1/10,94/100,1,0,0,0,0,8.1,94.0,filme,menores,menores
4,5,Roma,2018,18+,7.7/10,94/100,1,0,0,0,0,7.7,94.0,filme,maiores,menores
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9510,9511,Most Wanted Sharks,2020,NaN,NaN,14/100,0,0,0,1,0,NaN,14.0,filme,NaN,maiores
9511,9512,Doc McStuffins: The Doc Is In,2020,NaN,NaN,13/100,0,0,0,1,0,NaN,13.0,filme,NaN,maiores
9512,9513,Ultimate Viking Sword,2019,NaN,NaN,13/100,0,0,0,1,0,NaN,13.0,filme,NaN,maiores
9513,9514,Hunt for the Abominable Snowman,2011,NaN,NaN,10/100,0,0,0,1,0,NaN,10.0,filme,NaN,maiores
9514,9515,Women of Impact: Changing the World,2019,7+,NaN,10/100,0,0,0,1,0,NaN,10.0,filme,NaN,maiores

In [42]:
melhores_filmes = melhores_filmes[(melhores_filmes['Categ_IMDB']=="maiores")&\
(melhores_filmes['Categ_Rotten']=="maiores")].sort_values(["Ajuste_IMDB","Ajuste_Rotten"],ascending=False)

In [43]:
melhores_filmes

,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Type,Ajuste_IMDB,Ajuste_Rotten,tipo,Categ_IMDB,Categ_Rotten
3774,3775,The Conversation,1974,7+,7.8/10,77/100,0,1,0,0,0,7.8,77.0,filme,maiores,maiores
4769,4770,Jean-Michel Basquiat: The Radiant Child,2010,NaN,7.8/10,77/100,0,0,1,0,0,7.8,77.0,filme,maiores,maiores
276,277,The Outlaw Josey Wales,1976,7+,7.8/10,76/100,1,0,0,0,0,7.8,76.0,filme,maiores,maiores
3782,3783,The Man from Nowhere,2010,18+,7.8/10,76/100,0,1,0,0,0,7.8,76.0,filme,maiores,maiores
284,285,My Fair Lady,1964,all,7.8/10,75/100,1,0,0,0,0,7.8,75.0,filme,maiores,maiores
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9413,9414,Jonas Brothers: The Concert Experience,2009,all,1.6/10,43/100,0,0,0,1,0,1.6,43.0,filme,maiores,maiores
8511,8512,Terror at Bigfoot Pond,2020,18+,1.6/10,34/100,0,0,1,0,0,1.6,34.0,filme,maiores,maiores
8153,8154,Izzie's Way Home,2016,all,1.5/10,38/100,0,0,1,0,0,1.5,38.0,filme,maiores,maiores
3479,3480,Aerials,2016,NaN,1.5/10,36/100,1,0,0,0,0,1.5,36.0,filme,maiores,maiores
8394,8395,Finding Jesus,2020,all,1.1/10,36/100,0,0,1,0,0,1.1,36.0,filme,maiores,maiores